In [3]:
import pandas as pd
arquivo = pd.read_csv('C:/Users/Usuario/Downloads/wine_dataset.csv')

In [4]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [5]:
arquivo['style'] = arquivo['style'].replace('red', 0)
arquivo['style'] = arquivo['style'].replace('white', 1)

In [6]:
y = arquivo['style']
x = arquivo.drop('style', axis = 1)

In [7]:
!pip install sklearn

Requirement already satisfied: sklearn in c:\users\usuario\anaconda3\lib\site-packages (0.0.post7)

In [9]:
from sklearn.model_selection import train_test_split

xtr, xte, ytr, yte = train_test_split(x, y, test_size = 0.3)

In [10]:
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier()
modelo.fit(xtr, ytr)

resultado = modelo.score(xte, yte)
print("Acurácia:", resultado)

Acurácia: 0.9953846153846154

In [11]:
yte[100:110]

4844    1
1227    0
4388    1
5023    1
3648    1
2815    1
3731    1
3523    1
2858    1
3783    1
Name: style, dtype: int64

In [12]:
xte[100:110]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
4844,7.6,0.27,0.29,2.50,0.059,37.0,115.0,0.99328,3.09,0.37,9.8,5
1227,9.0,0.58,0.25,2.00,0.104,8.0,21.0,0.99769,3.27,0.72,9.6,5
4388,6.9,0.40,0.43,6.20,0.065,42.0,178.0,0.99552,3.11,0.53,9.4,5
5023,6.4,0.32,0.27,4.90,0.034,18.0,122.0,0.99160,3.36,0.71,12.5,6
3648,6.3,0.28,0.24,8.45,0.031,32.0,172.0,0.99580,3.39,0.57,9.7,7
2815,8.2,0.37,0.36,1.00,0.034,17.0,93.0,0.99060,3.04,0.32,11.7,8
3731,7.1,0.22,0.32,16.90,0.056,49.0,158.0,0.99980,3.37,0.38,9.6,6
3523,7.6,0.26,0.36,1.60,0.032,6.0,106.0,0.99300,3.15,0.40,10.4,4
2858,6.2,0.21,0.38,6.80,0.036,64.0,245.0,0.99510,3.06,0.36,9.3,6
3783,6.4,0.33,0.24,9.80,0.041,29.0,109.0,0.99560,3.29,0.47,10.1,6

In [13]:
previsoes = modelo.predict(xte[100:110])
previsoes

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)